import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': _english,
        'es_ES': _spanish,
      };

  final Map<String, String> _english = {
    "Choose your language": "Choose your language",
    "Select your preferred language": "Select your preferred language",
    "Discover a new world near you.": "Discover a new world near you.",
    "Get Started": "Get Started",
    "Life is short and the world is wide.\nSign in or register now!":
        "Life is short and the world is wide.\nSign in or register now!",
    "Never Miss a Spot": "Never Miss a Spot",
    "Find and visit the best nature near you.":
        "Find and visit the best nature near you.",
    "Email": "Email",
    "Password": "Password",
    "Enter Your Email": "Enter Your Email",
    "Enter your password": "Enter your password",
    "Sign Up": "Sign Up",
    "Remember Me": "Remember Me",
    "Forgot Password?": "Forgot Password?",
    "Sign In": "Sign In",
    "or sign in with": "or sign in with",
    "Don't have an account.   ": "Don't have an account.   ",
    "Enter your email below to reset your password":
        "Enter your email below to reset your password",
    "Verify": "Verify",
    "Reset Password": "Reset Password",
    "Enter the four-digit code that was emailed to you.":
        "Enter the four-digit code that was emailed to you.",
    "Create New Password": "Create New Password",
    "Your new password must be different from previous passwords.":
        "Your new password must be different from previous passwords.",
    "Confirm Password": "Confirm Password",
    "New Password": "New Password",
    "Enter New Password": "Enter New Password",
    "Enter Password": "Enter Password",
    "Save": "Save",
    "Password Changed!": "Password Changed!",
    "Return to the login page to enter your account with your new password.":
        "Return to the login page to enter your account with your new password.",
    "Continue": "Continue",
    "Registration": "Registration",
    "Create your account": "Create your account",
    "User Name": "User Name",
    "Enter User Name": "Enter User Name",
    "Date of birth": "Date of birth",
    "FAQ": "FAQ",
    "Terms & Conditions": "Terms & Conditions",
    "Privacy Policy": "Privacy Policy",
    "By creating an account, I accept the":
        "By creating an account, I accept the",
    "&": "&",
    "OR": "OR",
    "Register": "Register",
    "Google": "Google",
    "Enter Email": "Enter Email",
    "mm/ dd/ yyyy": "mm/ dd/ yyyy",
    "My Spots": "My Spots",
    "My Routes": "My Routes",
    "Favorite Sites": "Favorite Sites",
    "Favorite Routes": "Favorite Routes",
    "SETTINGS": "SETTINGS",
    "Language": "Language",
    "Change Password": "Change Password",
    "Delete account": "Delete account",
    "Manage Download": "Manage Download",
    "About Us": "About Us",
    "Logout": "Logout",
    "Points": "Points",
    "Are you sure you want to Logout?": "Are you sure you want to Logout?",
    "Yes": "Yes",
    "No": "No",
    "Want to Delete Account !": "Want to Delete Account !",
    "Please confirm your password to remove your account.":
        "Please confirm your password to remove your account.",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "Deleting...": "Deleting...",
    "Search in ZeroSignal": "Search in ZeroSignal",
    "Loading spots...": "Loading spots...",
    "Search Radius": "Search Radius",
    "Offline Map Download": "Offline Map Download",
    "Download map data for offline use?": "Download map data for offline use?",
    "This will allow you to use maps without internet connection. Perfect for areas with poor connectivity!":
        "This will allow you to use maps without internet connection. Perfect for areas with poor connectivity!",
    "Maps will be stored in your device storage":
        "Maps will be stored in your device storage",
    "Download": "Download",
    "Downloading offline map...": "Downloading offline map...",
    "Offline map downloaded successfully!":
        "Offline map downloaded successfully!",
    "Stored at": "Stored at",
    "Spot Details": "Spot Details",
    "Location not specified": "Location not specified",
    "user will visit this place on Sunday":
        "user will visit this place on Sunday",
    "Description": "Description",
    "No description available for this spot.":
        "No description available for this spot.",
    "Comments": "Comments",
    "Show less": "Show less",
    "See more": "See more",
    "Add a comment here....": "Add a comment here....",
    "Posting...": "Posting...",
    "Comment": "Comment",
    "Update Status": "Update Status",
    "How To Arrive": "How To Arrive",
    "Add Favorites": "Add Favorites",
    "Assist": "Assist",
    "Success": "Success",
    "Error": "Error",
    "You liked this user!": "You liked this user!",
    "Failed to like user.": "Failed to like user.",
    "Could not retrieve user details.": "Could not retrieve user details.",
    "Report User": "Report User",
    "Your report is anonymous. Please provide details about the issue to help our moderation team.":
        "Your report is anonymous. Please provide details about the issue to help our moderation team.",
    "Reason for reporting": "Reason for reporting",
    "e.g., inappropriate content, spam, harassment.....":
        "e.g., inappropriate content, spam, harassment.....",
    "Please enter a reason.": "Please enter a reason.",
    "Report submitted successfully": "Report submitted successfully",
    "Failed to submit report.": "Failed to submit report.",
    "Send to Administration": "Send to Administration",
    "No bio available": "No bio available",
    "View Profile": "View Profile",
    "Report user": "Report user",
    "No activities found": "No activities found",
    "people attending": "people attending",
    "attendants max.": "attendants max.",
    "Saved": "Saved",
    "Save": "Save",
    "Attendants": "Attendants",
    "No Attendants": "No Attendants",
    "Not today": "Not today",
    "I'm in!": "I'm in!",
    "Report Activity": "Report Activity",
    "Enter ": "Enter ",
    " digits code": " digits code",
    "Resend code in ": "Resend code in ",
    "Didn't receive code? ": "Didn't receive code? ",
    "Please enter the complete 4-digit code":
        "Please enter the complete 4-digit code",
    "Loading...": "Loading...",
    "Create Activity": "Create Activity",
    "Activity Title": "Activity Title",
    "Title of the activity": "Title of the activity",
    "Date": "Date",
    "dd/mm/yyyy": "dd/mm/yyyy",
    "Do you want to do a route of your favorites?":
        "Do you want to do a route of your favorites?",
    "Select route": "Select route",
    "Location": "Location",
    "Search place (Google Maps)": "Search place (Google Maps)",
    "Activity Type": "Activity Type",
    "Select type": "Select type",
    "Description of the activity ": "Description of the activity ",
    "max 5 photos": "max 5 photos",
    "Maximum Number of Attendees": "Maximum Number of Attendees",
    "Enter Number": "Enter Number",
    "Publish": "Publish",
    "Add Images": "Add Images",
    "Change Language": "Change Language",
    "Language changed to ": "Language changed to ",
    "Change password": "Change password",
    "Current Password": "Current Password",
    "Save Changes": "Save Changes",
    "Enter Current Password": "Enter Current Password",
    "Re-enter New Password": "Re-enter New Password",
    "Edit Profile": "Edit Profile",
    "Full Name": "Full Name",
    "Me in one sentence": "Me in one sentence",
    "Gender": "Gender",
    "Male": "Male",
    "Female": "Female",
    "Other": "Other",
    "Address": "Address",
    "yyyy-mm-dd": "yyyy-mm-dd",
    "Save & Continue": "Save & Continue",
    "Personal Information": "Personal Information",
    "km": "km",
    "Storage: ": "Storage: ",
    "This may take a few minutes": "This may take a few minutes",
    "0.5 km": "0.5 km",
    "30 km": "30 km",
    "Hiking Adventure": "Hiking Adventure",
    " participants": " participants",
    "No messages yet...": "No messages yet...",
    "Compose your message...": "Compose your message...",
    "Participants": "Participants",
    "Audio message": "Audio message",
    "Empty message": "Empty message",
    "Retry": "Retry",
    "No user data found": "No user data found",
    "Enter a description of the changes here....":
        "Enter a description of the changes here....",
    "Enter a route title": "Enter a route title",
    "Enter start location": "Enter start location",
    "Enter end location": "Enter end location",
    "Enter address to search...": "Enter address to search...",
    "Enter a title": "Enter a title",
    "Enter number of participants": "Enter number of participants",
    "Permission Required": "Permission Required",
    "Gallery access is required to pick images. Please enable it in settings.":
        "Gallery access is required to pick images. Please enable it in settings.",
    "Permission denied to access gallery":
        "Permission denied to access gallery",
    "Please enter a message": "Please enter a message",
  };

  final Map<String, String> _spanish = {
    "Choose your language": "Elige tu idioma",
    "Select your preferred language": "Selecciona tu idioma preferido",
    "Discover a new world near you.": "Descubre un nuevo mundo cerca de ti.",
    "Get Started": "Empezar",
    "Life is short and the world is wide.\nSign in or register now!":
        "La vida es corta y el mundo es ancho.\n¡Inicia sesión o regístrate ahora!",
    "Never Miss a Spot": "Nunca te pierdas un lugar",
    "Find and visit the best nature near you.":
        "Encuentra y visita la mejor naturaleza cerca de ti.",
    "Email": "Correo electrónico",
    "Password": "Contraseña",
    "Enter Your Email": "Introduce tu correo",
    "Enter your password": "Introduce tu contraseña",
    "Sign Up": "Regístrate",
    "Remember Me": "Recuérdame",
    "Forgot Password?": "¿Olvidaste tu contraseña?",
    "Sign In": "Iniciar sesión",
    "or sign in with": "o inicia sesión con",
    "Don't have an account.   ": "No tienes una cuenta.   ",
    "Enter your email below to reset your password":
        "Introduce tu correo abajo para restablecer tu contraseña",
    "Verify": "Verificar",
    "Reset Password": "Restablecer contraseña",
    "Enter the four-digit code that was emailed to you.":
        "Introduce el código de cuatro dígitos que te enviamos.",
    "Create New Password": "Crear nueva contraseña",
    "Your new password must be different from previous passwords.":
        "Tu nueva contraseña debe ser diferente de las anteriores.",
    "Confirm Password": "Confirmar contraseña",
    "New Password": "Nueva contraseña",
    "Enter New Password": "Introduce nueva contraseña",
    "Enter Password": "Introduce contraseña",
    "Save": "Guardar",
    "Password Changed!": "¡Contraseña cambiada!",
    "Return to the login page to enter your account with your new password.":
        "Vuelve a la página de inicio para entrar a tu cuenta con tu nueva contraseña.",
    "Continue": "Continuar",
    "Registration": "Registro",
    "Create your account": "Crea tu cuenta",
    "User Name": "Nombre de usuario",
    "Enter User Name": "Introduce nombre de usuario",
    "Date of birth": "Fecha de nacimiento",
    "FAQ": "Preguntas frecuentes",
    "Terms & Conditions": "Términos y condiciones",
    "Privacy Policy": "Política de privacidad",
    "By creating an account, I accept the": "Al crear una cuenta, acepto los",
    "&": "y",
    "OR": "O",
    "Register": "Registrarse",
    "Google": "Google",
    "Enter Email": "Introduce correo",
    "mm/ dd/ yyyy": "dd/ mm/ aaaa",
    "My Spots": "Mis lugares",
    "My Routes": "Mis rutas",
    "Favorite Sites": "Sitios favoritos",
    "Favorite Routes": "Rutas favoritas",
    "SETTINGS": "AJUSTES",
    "Language": "Idioma",
    "Change Password": "Cambiar contraseña",
    "Delete account": "Eliminar cuenta",
    "Manage Download": "Gestionar descargas",
    "About Us": "Sobre nosotros",
    "Logout": "Cerrar sesión",
    "Points": "Puntos",
    "Are you sure you want to Logout?":
        "¿Estás seguro de que quieres cerrar sesión?",
    "Yes": "Sí",
    "No": "No",
    "Want to Delete Account !": "¡Quieres eliminar tu cuenta!",
    "Please confirm your password to remove your account.":
        "Por favor confirma tu contraseña para eliminar tu cuenta.",
    "Cancel": "Cancelar",
    "Delete": "Eliminar",
    "Deleting...": "Eliminando...",
    "Search in ZeroSignal": "Buscar en ZeroSignal",
    "Loading spots...": "Cargando lugares...",
    "Search Radius": "Radio de búsqueda",
    "Offline Map Download": "Descargar mapa offline",
    "Download map data for offline use?":
        "¿Descargar datos del mapa para uso offline?",
    "This will allow you to use maps without internet connection. Perfect for areas with poor connectivity!":
        "Esto te permitirá usar mapas sin conexión a internet. ¡Perfecto para áreas con mala conectividad!",
    "Maps will be stored in your device storage":
        "Los mapas se guardarán en el almacenamiento de tu dispositivo",
    "Download": "Descargar",
    "Downloading offline map...": "Descargando mapa offline...",
    "Offline map downloaded successfully!":
        "¡Mapa offline descargado con éxito!",
    "Stored at": "Guardado en",
    "Spot Details": "Detalles del lugar",
    "Location not specified": "Ubicación no especificada",
    "user will visit this place on Sunday":
        "5 usuarios visitarán este lugar el domingo",
    "Description": "Descripción",
    "No description available for this spot.":
        "No hay descripción disponible para este lugar.",
    "Comments": "Comentarios",
    "Show less": "Mostrar menos",
    "See more": "Ver más",
    "Add a comment here....": "Añade un comentario aquí....",
    "Posting...": "Publicando...",
    "Comment": "Comentar",
    "Update Status": "Actualizar estado",
    "How To Arrive": "Cómo llegar",
    "Add Favorites": "Añadir a favoritos",
    "Assist": "Asistir",
    "Success": "Éxito",
    "Error": "Error",
    "You liked this user!": "¡Te gustó este usuario!",
    "Failed to like user.": "Error al dar like al usuario.",
    "Could not retrieve user details.":
        "No se pudieron obtener los detalles del usuario.",
    "Report User": "Reportar usuario",
    "Your report is anonymous. Please provide details about the issue to help our moderation team.":
        "Tu reporte es anónimo. Por favor proporciona detalles sobre el problema para ayudar a nuestro equipo de moderación.",
    "Reason for reporting": "Razón del reporte",
    "e.g., inappropriate content, spam, harassment.....":
        "ej., contenido inapropiado, spam, acoso.....",
    "Please enter a reason.": "Por favor introduce una razón.",
    "Report submitted successfully": "Reporte enviado con éxito",
    "Failed to submit report.": "Error al enviar reporte.",
    "Send to Administration": "Enviar a administración",
    "No bio available": "Sin biografía disponible",
    "View Profile": "Ver perfil",
    "Report user": "Reportar usuario",
    "No activities found": "No se encontraron actividades",
    "people attending": "personas asistiendo",
    "attendants max.": "asistentes máx.",
    "Saved": "Guardado",
    "Save": "Guardar",
    "Attendants": "Asistentes",
    "No Attendants": "Sin asistentes",
    "Not today": "No hoy",
    "I'm in!": "¡Me apunto!",
    "Report Activity": "Reportar actividad",
    "Enter ": "Introduce ",
    " digits code": " dígitos del código",
    "Resend code in ": "Reenviar código en ",
    "Didn't receive code? ": "¿No recibiste el código? ",
    "Please enter the complete 4-digit code":
        "Por favor introduce el código completo de 4 dígitos",
    "Loading...": "Cargando...",
    "Create Activity": "Crear actividad",
    "Activity Title": "Título de la actividad",
    "Title of the activity": "Título de la actividad",
    "Date": "Fecha",
    "dd/mm/yyyy": "dd/mm/aaaa",
    "Do you want to do a route of your favorites?":
        "¿Quieres hacer una ruta de tus favoritas?",
    "Select route": "Seleccionar ruta",
    "Location": "Ubicación",
    "Search place (Google Maps)": "Buscar lugar (Google Maps)",
    "Activity Type": "Tipo de actividad",
    "Select type": "Seleccionar tipo",
    "Description of the activity ": "Descripción de la actividad ",
    "max 5 photos": "máx 5 fotos",
    "Maximum Number of Attendees": "Número máximo de asistentes",
    "Enter Number": "Introduce número",
    "Publish": "Publicar",
    "Add Images": "Añadir imágenes",
    "Change Language": "Cambiar idioma",
    "Language changed to ": "Idioma cambiado a ",
    "Change password": "Cambiar contraseña",
    "Current Password": "Contraseña actual",
    "Save Changes": "Guardar cambios",
    "Enter Current Password": "Introduce contraseña actual",
    "Re-enter New Password": "Re-introduce nueva contraseña",
    "Edit Profile": "Editar perfil",
    "Full Name": "Nombre completo",
    "Me in one sentence": "Yo en una frase",
    "Gender": "Género",
    "Male": "Masculino",
    "Female": "Femenino",
    "Other": "Otro",
    "Address": "Dirección",
    "yyyy-mm-dd": "aaaa-mm-dd",
    "Save & Continue": "Guardar y continuar",
    "Personal Information": "Información personal",
    "km": "km",
    "Storage: ": "Almacenamiento: ",
    "This may take a few minutes": "Esto puede tardar unos minutos",
    "0.5 km": "0.5 km",
    "30 km": "30 km",
    "Hiking Adventure": "Aventura de senderismo",
    " participants": " participantes",
    "No messages yet...": "Todavía no hay mensajes...",
    "Compose your message...": "Escribe tu mensaje...",
    "Participants": "Participantes",
    "Audio message": "Mensaje de audio",
    "Empty message": "Mensaje vacío",
    "Retry": "Reintentar",
    "No user data found": "No se encontraron datos de usuario",
    "Enter a description of the changes here....":
        "Introduce una descripción de los cambios aquí....",
    "Enter a route title": "Introduce un título de ruta",
    "Enter start location": "Introduce ubicación de inicio",
    "Enter end location": "Introduce ubicación de fin",
    "Enter address to search...": "Introduce dirección para buscar...",
    "Enter a title": "Introduce un título",
    "Enter number of participants": "Introduce número de participantes",
    "Permission Required": "Permiso requerido",
    "Gallery access is required to pick images. Please enable it in settings.":
        "Se requiere acceso a la galería para elegir imágenes. Por favor habilítalo en ajustes.",
    "Permission denied to access gallery":
        "Permiso denegado para acceder a la galería",
    "Please enter a message": "Por favor introduce un mensaje",
  };
}
