import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': _english,
        'es_ES': _spanish,
      };

  final Map<String, String> _english = {
    'chooseYourLanguage': "Choose your language",
    'selectYourPreferredLanguage': "Select your preferred language",
    'discoverNewWorld': "Discover a new world near you.",
    'getStarted': "Get Started",
    'lifeIsShortAndSignIn':
        "Life is short and the world is wide.\nSign in or register now!",
    'neverMissASpot': "Never Miss a Spot",
    'findAndVisitNature': "Find and visit the best nature near you.",
    'email': "Email",
    'password': "Password",
    'enterYourEmail': "Enter Your Email",
    'enterYourPassword': "Enter your password",
    'signUp': "Sign Up",
    'rememberMe': "Remember Me",
    'forgotPassword': "Forgot Password?",
    'signIn': "Sign In",
    'orSignInWith': "or sign in with",
    'dontHaveAccount': "Don't have an account.   ",
    'resetPasswordInstruction': "Enter your email below to reset your password",
    'verify': "Verify",
    'resetPassword': "Reset Password",
    'enterFourDigitCode': "Enter the four-digit code that was emailed to you.",
    'createPassword': "Create New Password",
    'yourNewPassword':
        "Your new password must be different from previous passwords.",
    'confirmPassword': "Confirm Password",
    'newPassword': "New Password",
    'enterNewPassword': "Enter New Password",
    'enterPassword': "Enter Password",
    'save': "Save",
    'passwordChanged': "Password Changed!",
    'returnToLogin':
        "Return to the login page to enter your account with your new password.",
    'continueText': "Continue",
    'registration': "Registration",
    'createYourAccount': "Create your account",
    'userName': "User Name",
    'enterUserName': "Enter User Name",
    'dateOfBirth': "Date of birth",
    'faq': "FAQ",
    'termsAndConditions': "Terms & Conditions",
    'privacyPolicy': "Privacy Policy",
    'byCreatingAccountIAccept': "By creating an account, I accept the",
    'andText': "&",
    'orText': "OR",
    'register': "Register",
    'google': "Google",
    'userNameLabel': "User Name",
    'emailLabel': "Email",
    'enterUserEmail': "Enter Email",
    'dateOfBirthLabel': "Date of birth",
    'dateOfBirthHint': "mm/ dd/ yyyy",
    'passwordLabel': "Password",
    'mySpots': "My Spots",
    'myRoutes': "My Routes",
    'favoriteSites': "Favorite Sites",
    'favoriteRoutes': "Favorite Routes",
    'settings': "SETTINGS",
    'language': "Language",
    'changePassword': "Change Password",
    'deleteAccount': "Delete account",
    'manageDownload': "Manage Download",
    'aboutUs': "About Us",
    'privacyPolicyHeader': "Privacy Policy",
    'termsAndConditionsHeader': "Terms & Conditions",
    'faqHeader': "FAQ",
    'logout': "Logout",
    'points': "Points",
    'areYouSureLogout': "Are you sure you want to Logout?",
    'yes': "Yes",
    'no': "No",
    'wantToDeleteAccount': "Want to Delete Account !",
    'confirmPasswordToDelete':
        "Please confirm your password to remove your account.",
    'enterPasswordLabel': "Enter Password",
    'cancel': "Cancel",
    'delete': "Delete",
    'deleting': "Deleting...",
    'searchInZeroSignal': "Search in ZeroSignal",
    'loadingSpots': "Loading spots...",
    'searchRadius': "Search Radius",
    'offlineMapDownload': "Offline Map Download",
    'downloadMapDataOffline': "Download map data for offline use?",
    'offlineMapInstruction':
        "This will allow you to use maps without internet connection. Perfect for areas with poor connectivity!",
    'mapsStoredInDevice': "Maps will be stored in your device storage",
    'download': "Download",
    'downloadingOfflineMap': "Downloading offline map...",
    'offlineMapSuccess': "Offline map downloaded successfully!",
    'storedAt': "Stored at",
    'spotDetails': "Spot Details",
    'locationNotSpecified': "Location not specified",
    'visitorInfoPrefix': "user will visit this place on Sunday",
    'descriptionHeader': "Description",
    'noDescriptionAvailable': "No description available for this spot.",
    'commentsHeader': "Comments",
    'showLess': "Show less",
    'seeMore': "See more",
    'addCommentHint': "Add a comment here....",
    'posting': "Posting...",
    'commentButton': "Comment",
    'updateStatus': "Update Status",
    'howToArrive': "How To Arrive",
    'addFavorites': "Add Favorites",
    'assist': "Assist",
    'success': "Success",
    'error': "Error",
    'likedUserMessage': "You liked this user!",
    'failedToLikeUser': "Failed to like user.",
    'couldNotRetrieveUserDetails': "Could not retrieve user details.",
    'reportUser': "Report User",
    'reportInstruction':
        "Your report is anonymous. Please provide details about the issue to help our moderation team.",
    'reasonForReporting': "Reason for reporting",
    'reportPlaceholder': "e.g., inappropriate content, spam, harassment.....",
    'pleaseEnterReason': "Please enter a reason.",
    'reportSubmittedSuccessfully': "Report submitted successfully",
    'failedToSubmitReport': "Failed to submit report.",
    'sendToAdministration': "Send to Administration",
    'noBioAvailable': "No bio available",
    'viewProfile': "View Profile",
    'reportUserLabel': "Report user",
    'noActivitiesFound': "No activities found",
    'peopleAttending': "people attending",
    'attendantsMax': "attendants max.",
    'savedHeader': "Saved",
    'saveHeader': "Save",
    'attendantsHeader': "Attendants",
    'noAttendants': "No Attendants",
    'notToday': "Not today",
    'imIn': "I'm in!",
    'reportActivity': "Report Activity",
    'enterText': "Enter ",
    'digitsCode': " digits code",
    'enterCodeEmailMessage':
        "Enter the four-digit code that was emailed to you.",
    'resendCodeIn': "Resend code in ",
    'didNotReceiveCode': "Didn't receive code? ",
    'completeFourDigitCodeError': "Please enter the complete 4-digit code",
    'loading': "Loading...",
    'createActivity': "Create Activity",
    'activityTitle': "Activity Title",
    'titleOfActivityHint': "Title of the activity",
    'dateLabel': "Date",
    'dateHint': "dd/mm/yyyy",
    'routeQuestion': "Do you want to do a route of your favorites?",
    'selectRouteHint': "Select route",
    'locationLabel': "Location",
    'searchPlaceHint': "Search place (Google Maps)",
    'activityTypeLabel': "Activity Type",
    'selectTypeHint': "Select type",
    'descriptionOfActivityHint': "Description of the activity ",
    'maxPhotos': "max 5 photos",
    'maxAttendees': "Maximum Number of Attendees",
    'enterNumberHint': "Enter Number",
    'publish': "Publish",
    'addImages': "Add Images",
    'changeLanguageHeader': "Change Language",
    'languageChangedPrefix': "Language changed to ",
    'changePasswordHeader': "Change password",
    'currentPasswordLabel': "Current Password",
    'saveChanges': "Save Changes",
    'enterCurrentPassword': "Enter Current Password",
    'reEnterNewPassword': "Re-enter New Password",
    'editProfile': "Edit Profile",
    'fullName': "Full Name",
    'meInOneSentence': "Me in one sentence",
    'gender': "Gender",
    'male': "Male",
    'female': "Female",
    'other': "Other",
    'address': "Address",
    'yyyyMmDdHint': "yyyy-mm-dd",
    'saveAndContinue': "Save & Continue",
    'personalInformationHeader': "Personal Information",
    'km': "km",
    'storagePrefix': "Storage: ",
    'downloadInstruction': "This may take a few minutes",
    'zeroFiveKm': "0.5 km",
    'thirtyKm': "30 km",
    'hikingAdventure': "Hiking Adventure",
    'participantsSuffix': " participants",
    'noMessagesYet': "No messages yet...",
    'composeMessageHint': "Compose your message...",
    'participantsHeader': "Participants",
    'audioMessage': "Audio message",
    'emptyMessage': "Empty message",
    'retry': "Retry",
    'noUserDataFound': "No user data found",
    'enterDescriptionHint': "Enter a description of the changes here....",
    'enterRouteTitle': "Enter a route title",
    'enterStartLocation': "Enter start location",
    'enterEndLocation': "Enter end location",
    'enterAddressToSearch': "Enter address to search...",
    'enterTitle': "Enter a title",
    'enterNumberOfParticipants': "Enter number of participants",
    'permissionRequired': "Permission Required",
    'galleryAccessRequired':
        "Gallery access is required to pick images. Please enable it in settings.",
    'permissionDeniedGallery': "Permission denied to access gallery",
    'pleaseEnterMessage': "Please enter a message",
  };

  final Map<String, String> _spanish = {
    'chooseYourLanguage': "Elige tu idioma",
    'selectYourPreferredLanguage': "Selecciona tu idioma preferido",
    'discoverNewWorld': "Descubre un nuevo mundo cerca de ti.",
    'getStarted': "Empezar",
    'lifeIsShortAndSignIn':
        "La vida es corta y el mundo es ancho.\n¡Inicia sesión o regístrate ahora!",
    'neverMissASpot': "Nunca te pierdas un lugar",
    'findAndVisitNature': "Encuentra y visita la mejor naturaleza cerca de ti.",
    'email': "Correo electrónico",
    'password': "Contraseña",
    'enterYourEmail': "Introduce tu correo",
    'enterYourPassword': "Introduce tu contraseña",
    'signUp': "Regístrate",
    'rememberMe': "Recuérdame",
    'forgotPassword': "¿Olvidaste tu contraseña?",
    'signIn': "Iniciar sesión",
    'orSignInWith': "o inicia sesión con",
    'dontHaveAccount': "No tienes una cuenta.   ",
    'resetPasswordInstruction':
        "Introduce tu correo abajo para restablecer tu contraseña",
    'verify': "Verificar",
    'resetPassword': "Restablecer contraseña",
    'enterFourDigitCode':
        "Introduce el código de cuatro dígitos que te enviamos.",
    'createPassword': "Crear nueva contraseña",
    'yourNewPassword':
        "Tu nueva contraseña debe ser diferente de las anteriores.",
    'confirmPassword': "Confirmar contraseña",
    'newPassword': "Nueva contraseña",
    'enterNewPassword': "Introduce nueva contraseña",
    'enterPassword': "Introduce contraseña",
    'save': "Guardar",
    'passwordChanged': "¡Contraseña cambiada!",
    'returnToLogin':
        "Vuelve a la página de inicio para entrar a tu cuenta con tu nueva contraseña.",
    'continueText': "Continuar",
    'registration': "Registro",
    'createYourAccount': "Crea tu cuenta",
    'userName': "Nombre de usuario",
    'enterUserName': "Introduce nombre de usuario",
    'dateOfBirth': "Fecha de nacimiento",
    'faq': "Preguntas frecuentes",
    'termsAndConditions': "Términos y condiciones",
    'privacyPolicy': "Política de privacidad",
    'byCreatingAccountIAccept': "Al crear una cuenta, acepto los",
    'andText': "y",
    'orText': "O",
    'register': "Registrarse",
    'google': "Google",
    'userNameLabel': "Nombre de usuario",
    'emailLabel': "Correo",
    'enterUserEmail': "Introduce correo",
    'dateOfBirthLabel': "Fecha de nacimiento",
    'dateOfBirthHint': "dd/ mm/ aaaa",
    'passwordLabel': "Contraseña",
    'mySpots': "Mis lugares",
    'myRoutes': "Mis rutas",
    'favoriteSites': "Sitios favoritos",
    'favoriteRoutes': "Rutas favoritas",
    'settings': "AJUSTES",
    'language': "Idioma",
    'changePassword': "Cambiar contraseña",
    'deleteAccount': "Eliminar cuenta",
    'manageDownload': "Gestionar descargas",
    'aboutUs': "Sobre nosotros",
    'privacyPolicyHeader': "Política de privacidad",
    'termsAndConditionsHeader': "Términos y condiciones",
    'faqHeader': "Preguntas frecuentes",
    'logout': "Cerrar sesión",
    'points': "Puntos",
    'areYouSureLogout': "¿Estás seguro de que quieres cerrar sesión?",
    'yes': "Sí",
    'no': "No",
    'wantToDeleteAccount': "¡Quieres eliminar tu cuenta!",
    'confirmPasswordToDelete':
        "Por favor confirma tu contraseña para eliminar tu cuenta.",
    'enterPasswordLabel': "Introduce contraseña",
    'cancel': "Cancelar",
    'delete': "Eliminar",
    'deleting': "Eliminando...",
    'searchInZeroSignal': "Buscar en ZeroSignal",
    'loadingSpots': "Cargando lugares...",
    'searchRadius': "Radio de búsqueda",
    'offlineMapDownload': "Descargar mapa offline",
    'downloadMapDataOffline': "¿Descargar datos del mapa para uso offline?",
    'offlineMapInstruction':
        "Esto te permitirá usar mapas sin conexión a internet. ¡Perfecto para áreas con mala conectividad!",
    'mapsStoredInDevice':
        "Los mapas se guardarán en el almacenamiento de tu dispositivo",
    'download': "Descargar",
    'downloadingOfflineMap': "Descargando mapa offline...",
    'offlineMapSuccess': "¡Mapa offline descargado con éxito!",
    'storedAt': "Guardado en",
    'spotDetails': "Detalles del lugar",
    'locationNotSpecified': "Ubicación no especificada",
    'visitorInfoPrefix': "5 usuarios visitarán este lugar el domingo",
    'descriptionHeader': "Descripción",
    'noDescriptionAvailable': "No hay descripción disponible para este lugar.",
    'commentsHeader': "Comentarios",
    'showLess': "Mostrar menos",
    'seeMore': "Ver más",
    'addCommentHint': "Añade un comentario aquí....",
    'posting': "Publicando...",
    'commentButton': "Comentar",
    'updateStatus': "Actualizar estado",
    'howToArrive': "Cómo llegar",
    'addFavorites': "Añadir a favoritos",
    'assist': "Asistir",
    'success': "Éxito",
    'error': "Error",
    'likedUserMessage': "¡Te gustó este usuario!",
    'failedToLikeUser': "Error al dar like al usuario.",
    'couldNotRetrieveUserDetails':
        "No se pudieron obtener los detalles del usuario.",
    'reportUser': "Reportar usuario",
    'reportInstruction':
        "Tu reporte es anónimo. Por favor proporciona detalles sobre el problema para ayudar a nuestro equipo de moderación.",
    'reasonForReporting': "Razón del reporte",
    'reportPlaceholder': "ej., contenido inapropiado, spam, acoso.....",
    'pleaseEnterReason': "Por favor introduce una razón.",
    'reportSubmittedSuccessfully': "Reporte enviado con éxito",
    'failedToSubmitReport': "Error al enviar reporte.",
    'sendToAdministration': "Enviar a administración",
    'noBioAvailable': "Sin biografía disponible",
    'viewProfile': "Ver perfil",
    'reportUserLabel': "Reportar usuario",
    'noActivitiesFound': "No se encontraron actividades",
    'peopleAttending': "personas asistiendo",
    'attendantsMax': "asistentes máx.",
    'savedHeader': "Guardado",
    'saveHeader': "Guardar",
    'attendantsHeader': "Asistentes",
    'noAttendants': "Sin asistentes",
    'notToday': "No hoy",
    'imIn': "¡Me apunto!",
    'reportActivity': "Reportar actividad",
    'enterText': "Introduce ",
    'digitsCode': " dígitos del código",
    'enterCodeEmailMessage':
        "Introduce el código de cuatro dígitos que te enviamos.",
    'resendCodeIn': "Reenviar código en ",
    'didNotReceiveCode': "¿No recibiste el código? ",
    'completeFourDigitCodeError':
        "Por favor introduce el código completo de 4 dígitos",
    'loading': "Cargando...",
    'createActivity': "Crear actividad",
    'activityTitle': "Título de la actividad",
    'titleOfActivityHint': "Título de la actividad",
    'dateLabel': "Fecha",
    'dateHint': "dd/mm/aaaa",
    'routeQuestion': "¿Quieres hacer una ruta de tus favoritas?",
    'selectRouteHint': "Seleccionar ruta",
    'locationLabel': "Ubicación",
    'searchPlaceHint': "Buscar lugar (Google Maps)",
    'activityTypeLabel': "Tipo de actividad",
    'selectTypeHint': "Seleccionar tipo",
    'descriptionOfActivityHint': "Descripción de la actividad ",
    'maxPhotos': "máx 5 fotos",
    'maxAttendees': "Número máximo de asistentes",
    'enterNumberHint': "Introduce número",
    'publish': "Publicar",
    'addImages': "Añadir imágenes",
    'changeLanguageHeader': "Cambiar idioma",
    'languageChangedPrefix': "Idioma cambiado a ",
    'changePasswordHeader': "Cambiar contraseña",
    'currentPasswordLabel': "Contraseña actual",
    'saveChanges': "Guardar cambios",
    'enterCurrentPassword': "Introduce contraseña actual",
    'reEnterNewPassword': "Re-introduce nueva contraseña",
    'editProfile': "Editar perfil",
    'fullName': "Nombre completo",
    'meInOneSentence': "Yo en una frase",
    'gender': "Género",
    'male': "Masculino",
    'female': "Femenino",
    'other': "Otro",
    'address': "Dirección",
    'yyyyMmDdHint': "aaaa-mm-dd",
    'saveAndContinue': "Guardar y continuar",
    'personalInformationHeader': "Información personal",
    'km': "km",
    'storagePrefix': "Almacenamiento: ",
    'downloadInstruction': "Esto puede tardar unos minutos",
    'zeroFiveKm': "0.5 km",
    'thirtyKm': "30 km",
    'hikingAdventure': "Aventura de senderismo",
    'participantsSuffix': " participantes",
    'noMessagesYet': "Todavía no hay mensajes...",
    'composeMessageHint': "Escribe tu mensaje...",
    'participantsHeader': "Participantes",
    'audioMessage': "Mensaje de audio",
    'emptyMessage': "Mensaje vacío",
    'retry': "Reintentar",
    'noUserDataFound': "No se encontraron datos de usuario",
    'enterDescriptionHint': "Introduce una descripción de los cambios aquí....",
    'enterRouteTitle': "Introduce un título de ruta",
    'enterStartLocation': "Introduce ubicación de inicio",
    'enterEndLocation': "Introduce ubicación de fin",
    'enterAddressToSearch': "Introduce dirección para buscar...",
    'enterTitle': "Introduce un título",
    'enterNumberOfParticipants': "Introduce número de participantes",
    'permissionRequired': "Permiso requerido",
    'galleryAccessRequired':
        "Se requiere acceso a la galería para elegir imágenes. Por favor habilítalo en ajustes.",
    'permissionDeniedGallery': "Permiso denegado para acceder a la galería",
    'pleaseEnterMessage': "Por favor introduce un mensaje",
  };
}
